### ISSUE TITLE
[F] 프로젝트 기본 설정 추가

### ISSUE THREAD

**Issue by vincent-kk** [RootSearch/mood-tracker-app#1]
## Overview

RN 기본 템플릿의 초기 설정을 진행

---

## Detail

- RN 탬플릿을 기반으로 기본적인 라우터와 페이지를 추가
- 필수적으로 사용되는 패키지 추가
- 의존성 패키지 구분

---

## Note

별도의 PR을 만들지 않고 master branch에 바로 commit, 기존 commit 정리

**Comment by bennlee** [comment]
@KLumy 
- [x] `develop` 으로 `master` 커밋들 적당히 cherry-pick 한 후, master 날려주십샤 🙏

**Comment by vincent-kk** [comment]
@bennlee 
생각해보니 그냥 했어도 됬는데 일단 PR을 넣었습니다.
한번 정도는 디렉토리 구조를 설명하고 가는게 좋을 것 같아서...
일단 매우 늦어서 대단히 죄송합니다 🙏
